databases:
- host: HOSTorIP
  database: DATABASENAME
  user: USERNAME
  password: PASSWORD
  preparedStatments:
   - name: GENERIC_NAME
     text: SQl_STATEMENT
     values: ARRAY_OF_PARAMATERS
- host: HOSTorIP
  database: DATABASENAME
  user: USERNAME
  password: PASSWORD
  preparedStatments:
   - name: GENERIC_NAME
     text: SQl_STATEMENT
     values: ARRAY_OF_PARAMATERS
