databases:
- host: HOSTORIP
  database: DATABASENAME
  user: USERNAME
  pasword: PASSWORD
  sqlfiles:
    - sqlfile: sql/SQLFILE.sql
- host: HOSTORIP
  database: DATABASENAME
  user: USERNAME
  pasword: PASSWORD
  sqlfiles:
    - sqlfile: sql/SQLFILE.sql
